apiVersion: v1
kind: Service
metadata:
  name: docker-demo-service
spec:
  selector:
    app: docker-demo
  type: LoadBalancer   # ✅ works with minikube tunnel
  ports:
    - port: 8080       # Service port
      targetPort: 8080 # Container port
