apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
        - name: docker-demo
          image: lithesh28/docker-demo:latest   # ✅ matches workflow push
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /greet
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /greet
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
