apiVersion: v1
kind: Service
metadata:
  name: docker-demo-service
spec:
  selector:
    app: docker-demo
  type: NodePort   # expose via NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
